### ISSUE TITLE
require not working in mac os

### ISSUE THREAD

**Issue by jimthunderbird** [rpbouman/mysqlv8udfs#5]
Hi,
    I just installed mysqlv8udfs and i tried some simple examples and it works.
   But when I try to use the require example, things are not working.
    In my Mac, i have a folder ~/mysqlv8udf_samples
    And I have the following files and directories:
    json_export.sql
    js_modules/json_export.js
    In json_export.sql, I simply do:
   select jsagg('require("json_export.js");', id, name) as json from test.category;
   But when I run mysql < json_export.sql, from the mysql error log I got:
   Module not found
  js_modules/json_export.js 
  oops, file is NULL

**Comment by rpbouman** [comment]
Hi! sorry to find your issue so late. 
Have you tried setting the js_daemon_module_path server variable? Just put a line in your my.cnf, with js_daemon_module_path=/home/user/mysqlv8udf_samples (or wherever you want to put the scripts)

To be sure the setting is current, do a SHOW VARIABLES LIKE 'js%' to ensure the setting is correct.

**Comment by rpbouman** [comment]
@jimthunderbird Can you please read my previous comment and let me know if that solves it? I have no access to Mac so I cannot reproduce this myself. TIA, Roland.

**Comment by passionke** [comment]
@rpbouman, I have the same problem, and I solved it with your solutions, thnks

**Comment by rpbouman** [comment]
@passionke Thanks for the reply! Since I never heard back from @jimthunderbird  I'm going to assume your reply means the problem is solved. Reopen if the problem persists. Thank you!
